create table if not exists public.staging_patients (
  hospital_id uuid not null,
  patient_key text not null,
  name text,
  cns text,
  cpf text,
  birth_date date,
  gender text,
  address text,
  city text,
  state text,
  zip_code text,
  phone text,
  email text,
  blood_type text,
  allergies text,
  medical_notes text,
  is_active boolean,
  medical_record varchar,
  nationality varchar,
  mother_name varchar,
  neighborhood varchar,
  responsible_name varchar,
  document_type varchar,
  document_number varchar,
  race_color varchar,
  address_complement varchar,
  municipality varchar,
  state_uf varchar,
  postal_code varchar,
  prontuario varchar,
  nacionalidade varchar,
  raca_cor varchar,
  tipo_documento varchar,
  documento varchar,
  nome_responsavel varchar,
  nome_mae varchar,
  numero_endereco varchar,
  complemento_endereco varchar,
  bairro varchar,
  numero varchar,
  complemento varchar,
  telefone varchar
);

create index if not exists idx_staging_patients_hospital_key on public.staging_patients (hospital_id, patient_key);

create table if not exists public.staging_aihs (
  hospital_id uuid not null,
  aih_number text not null,
  patient_key text,
  procedure_code varchar,
  admission_date timestamptz,
  discharge_date timestamptz,
  estimated_discharge_date timestamptz,
  main_cid text,
  secondary_cid text[],
  professional_cbo text,
  requesting_physician text,
  original_value bigint,
  processing_status text,
  match_found boolean,
  rejection_reason text,
  requires_manual_review boolean,
  source_file text,
  import_batch_id uuid,
  authorization_date date,
  cns_authorizer varchar,
  cns_requester varchar,
  cns_responsible varchar,
  procedure_requested varchar,
  procedure_changed boolean,
  discharge_reason varchar,
  specialty varchar,
  care_modality varchar,
  care_character varchar,
  estimated_original_value integer,
  aih_anterior varchar,
  aih_posterior varchar,
  competencia date,
  situacao varchar,
  tipo varchar,
  data_autorizacao timestamptz,
  motivo_encerramento varchar,
  cns_autorizador varchar,
  cns_solicitante varchar,
  cns_responsavel varchar,
  procedimento_solicitado varchar,
  mudanca_procedimento boolean,
  especialidade varchar,
  modalidade varchar,
  caracter_atendimento varchar
);

create index if not exists idx_staging_aihs_hospital_aih on public.staging_aihs (hospital_id, aih_number);

create table if not exists public.staging_procedure_records (
  hospital_id uuid not null,
  aih_number text not null,
  patient_key text,
  procedure_code varchar,
  procedure_name varchar,
  procedure_description text,
  procedure_date timestamptz,
  execution_date timestamptz,
  authorization_number varchar,
  quantity integer,
  sequencia integer,
  value_charged bigint,
  unit_value integer,
  total_value integer,
  professional_name varchar,
  professional_cns varchar,
  professional_cbo varchar,
  professional text,
  billing_status varchar,
  billing_date timestamptz,
  payment_date timestamptz,
  notes text,
  descricao_original text,
  match_status varchar,
  match_confidence integer,
  observacoes text,
  care_modality varchar,
  care_character varchar,
  status varchar,
  authorization_type varchar,
  cnes varchar,
  codigo_procedimento_original varchar,
  competencia date
);

create index if not exists idx_staging_procs_hospital_aih on public.staging_procedure_records (hospital_id, aih_number);
